config/routes.rb
Rails.application.routes.draw do

  resource :user, only: [:create, :new, :show] do
    resources :circles
    resources :posts
  end

  resource :session, only: [:create, :new, :destroy]

end

app/models/circle.rb
class Circle < ActiveRecord::Base
  has_many :memberships, :inverse_of => :circle,
    class_name: "CircleMembership",
    foreign_key: :circle_id,
    primary_key: :id

  belongs_to :owner, :inverse_of => :owned_circles,
    class_name: "User",
    foreign_key: :owner_id,
    primary_key: :id

  has_many :members,
    through: :memberships,
    source: :member

  has_many :post_shares, :inverse_of => :circle,
    class_name: "PostShare",
    foreign_key: :circle_id,
    primary_key: :id

  has_many :posts,
    through: :post_shares,
    source: :post

  validates :owner_id, :name, presence: true
  validates :name, uniqueness: { scope: :owner_id}

end

app/models/circle_membership.rb
class CircleMembership < ActiveRecord::Base

  belongs_to :member, :inverse_of => :memberships,
    class_name: "User",
    foreign_key: :member_id,
    primary_key: :id

  belongs_to :circle, :inverse_of => :memberships,
    class_name: "Circle",
    foreign_key: :circle_id,
    primary_key: :id

end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :post, :inverse_of => :links,
    class_name: "Post",
    foreign_key: :post_id,
    primary_key: :id

  validates :address, :post_id, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, :inverse_of => :posts,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id

  has_many :links, :inverse_of => :post,
    class_name: "Link",
    foreign_key: :post_id,
    primary_key: :id

  has_many :post_shares, :inverse_of => :post,
    class_name: "PostShare",
    foreign_key: :post_id,
    primary_key: :id

  has_many :shared_circles,
    through: :post_shares,
    source: :circle

  validates :user_id, :body, presence: true
end

app/models/post_share.rb
class PostShare < ActiveRecord::Base
  belongs_to :post, :inverse_of => :post_shares,
    class_name: "Post",
    foreign_key: :post_id,
    primary_key: :id

  belongs_to :circle, :inverse_of => :post_shares,
    class_name: "Circle",
    foreign_key: :circle_id,
    primary_key: :id

  validates :circle_id, :post_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :owned_circles, :inverse_of => :owner,
    class_name: "Circle",
    foreign_key: :owner_id,
    primary_key: :id

  has_many :memberships, :inverse_of => :member,
    class_name: "CircleMembership",
    foreign_key: :member_id,
    primary_key: :id

  has_many :posts,
    class_name: "Post",
    foreign_key: :user_id,
    primary_key: :id

  has_many :belonged_circles, through: :memberships, source: :circle

  after_initialize :ensure_session_token

  validates :email, :password_digest, :session_token, presence: true
  validates :email, :session_token, uniqueness: true

  attr_reader :password

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def self.find_by_credentials(email, password)
    user = self.find_by_email(email)
    (user && user.is_password?(password)) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :signed_in?

  def sign_in!(user)
    session[:session_token] = user.session_token
  end

  def sign_out!
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end

  def signed_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def require_user!
    redirect_to new_session_url unless signed_in?
  end

end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController

  def index
  end

  def show
    @circle = Circle.find(params[:id])
    render :show
  end

  def create
    @circle = current_user.owned_circles.build(circle_params)

    if @circle.save
      redirect_to user_circle_url(@circle)
    else
      flash.now[:errors] = @circle.errors.full_messages
      render :new
    end
  end

  def new
    @circle = Circle.new
    render :new
  end

  def update
  end

  def edit
  end

  def destroy
  end

  private

  def circle_params
    params.require(:circle).permit(:owner_id, :name, member_ids: [])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def create
    @post = current_user.posts.build(post_params)
    @post.links.build(link_params)

    if @post.save
      # redirect_to...
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def new
    @post = Post.new
    render :new
  end

  def show

  end

  def edit

  end

  def destroy

  end

  def index

  end

  def update

  end

  private

  def post_params
    params.require(:post).permit(:body, :user_id, shared_circle_ids: [])
  end

  def link_params
    params.permit(links: :address)
          .require(:links)
          .values
          .reject { |data| data.values.all?(&:blank?) }
  end

  # def circle_params
  #   circle_ids = params.require(:post)
  #     .permit(shared_circles_id: []).values.flatten
  #   circle_ids.each_with_object([]) do |value, array|
  #     array << { "circle_id" => value }
  #   end
  # end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by_credentials(
      params[:session][:email],
      params[:session][:password]
    )

    if @user.nil?
      flash.now[:errors] = ["Invalid email/password combination"]
      render :new
    else
      #will become a user's feed
      sign_in!(@user)
      redirect_to user_circles_url
    end
  end

  def new
    @user = User.new
    render :new
  end

  def destroy
    sign_out!
    @user = User.new
    render :new
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in!(@user)
      #will leed to user's feed
      redirect_to user_circles_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def authenticity_token
    <<-HTML.html_safe
      <input type="hidden" name="authenticity_token"
        value="#{form_authenticity_token}">
    HTML
  end

end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/circles/index.html.erb
<h1>Your circles</h1>

<ul>
  <% current_user.owned_circles.each do |circle| %>
    <li><%= circle.name %></li>
  <% end %>
</ul>
<br>
<%= link_to "Create a new circle", action = new_user_circle_url  %><br>
<%= link_to "Make a new post", action = new_user_post_url  %>

app/views/circles/new.html.erb
<h1>Create your circle!</h1>

<form action="<%= user_circles_url %>" method="post">
  <%= authenticity_token %>

  <label>Name:
    <input type="text" name="circle[name]" value="<%= @circle.name %>">
  </label>
  <br>

<% User.all.each do |user| %>
  <% next if user == current_user %>
  <label>
    <input type="checkbox"
           name="circle[member_ids][]"
           value="<%= user.id %>">
   <%= user.email %>
  </label>
  <br>
<% end %>

  <input type="submit">
</form>

app/views/circles/show.html.erb
<h1><%= @circle.name.capitalize %> Circle</h1>

<ul>
  <% @circle.members.each do |member| %>
  <li><%= member.email %></li>
  <% end %>
</ul>

<a href="<%= "#" %>">Edit circle</a>

app/views/layouts/_flash_messages.html.erb
<% unless flash.empty? %>
  <ul>
  <% flash[:errors].each do |value| %>
    <li><%= value %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/flash_messages" %>
  <% if signed_in? %>
    <h3><%= current_user.email %></h3>
    <form action="<%= session_url %>" method="post">
      <%= authenticity_token %>
      <input type="hidden" name="_method" value="delete">
      <button>Sign out</button>
    </form>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/posts/new.html.erb
<h1>New Post</h1>
<form action="<%= user_posts_url %>" method="post">
  <%= authenticity_token %>

  <label>Post:<br>
    <textarea name="post[body]"><%= @post.body %></textarea>
    <br>
  </label>
<br>
  <label>Links:<br>
    <input type="text" name="links[1][address]"><br>
    <input type="text" name="links[2][address]"><br>
    <input type="text" name="links[3][address]"><br>
  </label>

<% current_user.owned_circles.each do |circle| %>
  <label><%= circle.name %>
    <input type="checkbox"
           name="post[shared_circle_ids][]"
           value="<%= circle.id %>">
  </label>
<% end %>

  <button>Post</button>
</form>

app/views/users/new.html.erb
<h1>Sign up!</h1>
<form action="<%= user_url %>" method="post">
  <%= authenticity_token %>

  <label>Email:
    <input type="text"
           value="<%= @user.email %>"
           name="user[email]">
  </label>
  <br>

  <label>Password:
    <input type="password"
           value=""
           name="user[password]">
  </label>
  <br>

  <button>Sign up</button>
</form>

<span>Already a user? Sign in <a href="<%= new_session_url %>">here</a>.</span>